from typing import Any, Protocol
from Package.AgentMemory.Src.Application.Dto.Contracts import RetrievalResult, WriteResult
from Package.AgentMemory.Src.Application.Dto.MemoryRecord import MemoryRecord


class MemoryApi(Protocol):
    def remember(self, content: str, scope: str = "project", **attributes: Any) -> MemoryRecord: ...
    def capture_turn(self, task: str, messages: list[dict], **context: Any) -> str: ...
    def retrieve(self, query: str, **options: Any) -> RetrievalResult: ...
    def run_jobs(self, limit: int = 10) -> dict: ...
    def export(self, destination: str) -> dict: ...

